services:
  db:
    image: postgres:16
    container_name: memo_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memo_app
    ports:
      - "5432:5432"
    volumes:
      - memo_app_db_data:/var/lib/postgresql/data

volumes:
  memo_app_db_data:
